/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module storevalues_18 (
    input clk,
    input selA,
    input selB,
    input store_or_show,
    input [7:0] switches1,
    input [7:0] switches0,
    output reg [15:0] outA,
    output reg [15:0] outB
  );
  
  
  
  wire [1-1:0] M_detectA_out;
  reg [1-1:0] M_detectA_in;
  edge_detector_2 detectA (
    .clk(clk),
    .in(M_detectA_in),
    .out(M_detectA_out)
  );
  wire [1-1:0] M_detectB_out;
  reg [1-1:0] M_detectB_in;
  edge_detector_2 detectB (
    .clk(clk),
    .in(M_detectB_in),
    .out(M_detectB_out)
  );
  wire [1-1:0] M_buttonA_out;
  button_conditioner_5 buttonA (
    .clk(clk),
    .in(selA),
    .out(M_buttonA_out)
  );
  wire [1-1:0] M_buttonB_out;
  button_conditioner_5 buttonB (
    .clk(clk),
    .in(selB),
    .out(M_buttonB_out)
  );
  reg [15:0] M_memoryA_d, M_memoryA_q = 1'h0;
  reg [15:0] M_memoryB_d, M_memoryB_q = 1'h0;
  
  always @* begin
    M_memoryA_d = M_memoryA_q;
    M_memoryB_d = M_memoryB_q;
    
    M_detectA_in = M_buttonA_out;
    M_detectB_in = M_buttonB_out;
    if (store_or_show == 1'h1) begin
      if (M_detectA_out) begin
        M_memoryA_d[8+7-:8] = switches1;
        M_memoryA_d[0+7-:8] = switches0;
      end
      if (M_detectB_out) begin
        M_memoryB_d[8+7-:8] = switches1;
        M_memoryB_d[0+7-:8] = switches0;
      end
      outA = M_memoryA_q;
      outB = M_memoryB_q;
    end else begin
      outA = M_memoryA_q;
      outB = M_memoryB_q;
    end
  end
  
  always @(posedge clk) begin
    M_memoryA_q <= M_memoryA_d;
    M_memoryB_q <= M_memoryB_d;
  end
  
endmodule
